# Generated by Django 5.0.6 on 2024-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_text_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_text_post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
