# Generated by Django 5.0.6 on 2024-07-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_create_musuic_post_create_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_musuic_post',
            old_name='video_title',
            new_name='musuic_text',
        ),
        migrations.RenameField(
            model_name='create_photo_post',
            old_name='video_title',
            new_name='photo_text',
        ),
    ]
